version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    branches:
      only:
        - master
    working_directory: ~/fdsl-test
    steps:
      - checkout
      - run:
          name: Checkout state-engine
          command: |
            pushd ~/
            git clone https://github.com/Fluxengin/state-engine.git
            popd
      - restore_cache:
          keys:
            - v1-m2-{{ checksum "~/state-engine/fluxengine-local-test-runner/pom.xml" }}-{{ checksum "~/state-engine/fluxengine-parser/pom.xml" }}-{{ checksum "~/state-engine/stateengine/pom.xml" }}
            - v1-m2-
      - run:
          name: Build test runner
          command: |
            for projectDir in stateengine fluxengine-parser
            do
            pushd ~/state-engine/$projectDir
            mvn install -U
            popd
            done
            pushd ~/state-engine/fluxengine-local-test-runner
            mvn package -U
            popd
      - save_cache:
          key: v1-m2-{{ checksum "~/state-engine/fluxengine-local-test-runner/pom.xml" }}-{{ checksum "~/state-engine/fluxengine-parser/pom.xml" }}-{{ checksum "~/state-engine/stateengine/pom.xml" }}
          paths:
            - ~/.m2
      - run:
          name: Replace test runner
          command: |
            rm -f fluxengine-local-test/lib/fluxengine-local-test-runner-*.jar
            cp -f ~/state-engine/fluxengine-local-test-runner/target/fluxengine-local-test-runner-*.jar fluxengine-local-test/lib/
            diff -q ~/state-engine/fluxengine-local-test-runner/target/fluxengine-local-test-runner-*.jar fluxengine-local-test/lib/fluxengine-local-test-runner-*.jar
      - restore_cache:
          keys:
            - v1-gradle-{{ .Branch }}-{{ checksum "fluxengine-local-test/build.gradle" }}
            - v1-gradle-{{ .Branch }}-
            - v1-gradle-
      - run:
          name: Build test
          command: |
            pushd fluxengine-local-test
            gradle build -x test
            popd
      - save_cache:
          key: v1-gradle-{{ .Branch }}-{{ checksum "fluxengine-local-test/build.gradle" }}
          paths:
            - ~/.gradle
      - run:
          name: テストの実施
          command: |
            pushd fluxengine-local-test
            export CONF=`pwd`/conf/
            gradle test
            popd
      - store_artifacts:
          path: fluxengine-local-test/build/reports/tests/test
