version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "fluxengine-local-test/build.gradle" }}
            - v1-dependencies-{{ .Branch }}-
            - v1-dependencies-
      - run: cd ~/repo/fluxengine-local-test && gradle build -x test
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ .Branch }}-{{ checksum "fluxengine-local-test/build.gradle" }}
      - run:
          name: テストの実施
          command: cd ~/repo/fluxengine-local-test && gradle test
      - store_artifacts:
          path: ~/repo/fluxengine-local-test/build/reports/tests/test
