version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run: rm -f ~/repo/fluxengine-local-test/lib/fluxengine-local-test-runner-*.jar
      - run: if [ -d ~/engine ]; then rm -rf ~/engine; fi; mkdir ~/engine
      - run: cd ~/engine && git clone https://github.com/Fluxengin/state-engine.git
      - run: cd ~/engine/state-engine/stateengine && mvn install && cd ~/engine/state-engine/fluxengine-parser && mvn install
      - run: cd ~/engine/state-engine/fluxengine-local-test-runner && mvn package && cp -f ~/engine/state-engine/fluxengine-local-test-runner/target/fluxengine-local-test-runner-*.jar ~/repo/fluxengine-local-test/lib/
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "fluxengine-local-test/build.gradle" }}
            - v1-dependencies-{{ .Branch }}-
            - v1-dependencies-
      - run: cd ~/repo/fluxengine-local-test && gradle build -x test
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ .Branch }}-{{ checksum "fluxengine-local-test/build.gradle" }}
      - run:
          name: テストの実施
          command: cd ~/repo/fluxengine-local-test/conf && export CONF=`pwd` && cd .. && gradle test
      - store_artifacts:
          path: ~/repo/fluxengine-local-test/build/reports/tests/test
